---
title: Patrícia's Resume"
author: Patrícia do Nascimento
date: "`r Sys.Date()`"
output:
  pagedown::html_resume:
    css: ['css/custom_resume.css', 'css/styles.css', 'resume']
    # set it to true for a self-contained HTML page but it'll take longer to render
    self_contained: true
---


```{r, include=FALSE}
knitr::opts_chunk$set(
  results='asis', 
  echo = FALSE
)
library(tidyverse)
library(glue)

# Set this to true to have links turned into footnotes at the end of the document
PDF_EXPORT <- TRUE 

# Holds all the links that were inserted for placement at the end
links <- c()

source('parsing_functions.R')


# First let's get the data, filtering to only the items tagged as
# Resume items
position_data <- read_csv('positions.csv') %>% 
  filter(in_resume) %>% 
  mutate(
    # Build some custom sections by collapsing others
    section = case_when(
      section %in% c('job_positions', 'teaching_positions') ~ 'positions', 
      section %in% c('online') ~ 'extra',
      TRUE ~ section
    )
  ) 

```


Aside
================================================================================


Contact {#contact}
--------------------------------------------------------------------------------



- <i class="fa fa-envelope"></i> pathilink@gmail.com
<!-- - <i class="fa fa-twitter"></i> Twitter: @pathilink -->
- <i class="fa fa-github"></i> GitHub [/pathilink](https://github.com/pathilink/)
- <i class="fas fa-globe"></i> Portfolio [/pathilink](https://pathilink.github.io/)
- <i class="fab fa-kaggle"></i> Kaggle [/pathilink](https://www.kaggle.com/pathilink)
- <i class="fab fa-linkedin-in"></i> LinkedIn [/pathilink](https://www.linkedin.com/in/pathilink/)
- <i class="fa fa-phone"></i> +55 11 _____ ____



Hard Skills {#skills}
--------------------------------------------------------------------------------


```{r}
skills <- tribble(
  ~skill,               ~level,
  "Python",             0,
  "R",                  0,
  "SQL",                0
  
)
build_skill_bars(skills)
```

Projects {#open-source}
--------------------------------------------------------------------------------

Projects available at `github.com/pathilink/<name>`


- `Kaggle/tree/master/world_ happiness`: Exploratory data analysis about happiness in the world. 

- `Kaggle/blob/master/glass door_br.ipynb`: Word cloud about data area.



Idioms {#skills}
--------------------------------------------------------------------------------


```{r}
skills <- tribble(
  ~skill,               ~level,
  "Portuguese",          0,
  "English",             0,
  "Spanish",             0
  
)
build_skill_bars(skills)
```


Volunteering {#open-source}
--------------------------------------------------------------------------------
[/PyLadiesSP](https://www.linkedin.com/company/pyladiessp/)


Disclaimer {#disclaimer}
--------------------------------------------------------------------------------

Made with [**pagedown**](https://github.com/rstudio/pagedown). 

Code available at [github.com/pathilink/cv](https://github.com/pathilink/cv).

Updated `r Sys.Date()`.




Main
================================================================================

Patrícia do Nascimento {#title}
--------------------------------------------------------------------------------

```{r}
intro_text <- 
"DATA ANALYST

"


cat(sanitize_links(intro_text))    # uncomment to print intro_text
```



Education {data-icon=graduation-cap data-concise=true}
--------------------------------------------------------------------------------

```{r}
position_data %>% print_section('education')
```



extracurricular {data-icon=laptop} 
--------------------------------------------------------------------------------


```{r}
position_data %>% print_section('extra')
```



Work experience {data-icon=suitcase}
--------------------------------------------------------------------------------

```{r}
position_data %>% print_section('positions')
```


